language: erlang
notifications:
  email: ward@tty.nl
otp_release:
  - R15B01
  - R15B
  - R14B04
script: env && rebar compile && rebar skip_deps=true eunit && rebar skip_deps=true ct
after_script: tar cvfz test_log.tar .eunit/ logs/ && curl -F "filedata=@test_log.tar" http://ci_asset_helper.equanimity.nl/
